# Generated by Django 5.1.4 on 2026-04-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color_theme',
            field=models.CharField(default='#ac2376', help_text='Hex color for event page', max_length=7),
        ),
    ]
