# Generated by Django 5.2 on 2026-04-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkin_open',
            field=models.BooleanField(default=True, help_text='When OFF, the QR scanner will reject new check-ins. All previously checked-in records remain intact.'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open',
            field=models.BooleanField(default=True, help_text='When OFF, the public registration form is closed. All existing registrations and QR codes remain intact.'),
        ),
    ]
