# Generated by Django 5.2 on 2026-04-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('events', '0002_alter_event_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='assigned_events',
            field=models.ManyToManyField(blank=True, help_text='Leave empty for superadmins (they see all). Assign specific events for admin/moderator roles.', related_name='assigned_admins', to='events.event'),
        ),
    ]
