# Generated by Django 5.2 on 2026-05-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='external_qr_id',
            field=models.CharField(blank=True, db_index=True, help_text='External QR code ID from another system (Eventbrite, Google Forms, etc.)', max_length=500, null=True),
        ),
    ]
